---
# tasks file for ssh
- name: update and upgrade
  yum:
    name: '*'
    state: latest

- name: Add deploy user
  user: name={{ centos_common_deploy_user_name }} password="{{ CENTOS_COMMON_DEPLOY_PASSWORD }}" shell=/bin/bash

- name: Add authorized keys for deploy user
  authorized_key: user={{ centos_common_deploy_user_name }}
                  key="{{ lookup('file', item) }}"
  with_items: centos_common_deploy_public_keys

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers
              regexp="{{ centos_common_deploy_user_name }} ALL"
              line="{{ centos_common_deploy_user_name }} ALL=(ALL) ALL"
              state=present